import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Task from '../components/Task'

const Home: NextPage = () => {
  return (
    <div className='box-border overflow-y-scroll snap-y snap-mandatory scrollbar-hide'>
      <Head>
        <title>DevsUI 🌩️ </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconhttps://www.getdroidtips.com/realme-narzo-10a-firmware-flash-file/#google_vignette.ico" />
      </Head>
      <div className="w-screen h-screen ">
        <Header />
        <div className="w-screen h-screen flex flex-col items-center justify-start pt-[11vh] snap-center">
          <img src="/Assets/images/discord.png" alt="discord" className="self-center w-[85%] h-[16%] min-h-[130px] rounded-[15px] mb-[20px]" />
          <div className="flex flex-col items-center justify-start">
            <img src="/Assets/lightmode/choose-icon.png" className="w-[20%]" />
            <span className="text-[20px] max-w-[60%] text-center mt-[7px] mb-[7px]">Choose your topic or design from us</span>
            <img src="/Assets/lightmode/design-dev.png" className="w-[22%] " />
            <span className="text-[20px] max-w-[60%] text-center mt-[7px] mb-[7px]">Develop or design your item</span>
            <img src="/Assets/lightmode/publish-icon.png" className="w-[19%] " />
            <span className="text-[20px] max-w-[60%] text-center mt-[7px] mb-[7px]">Publish on our site and support others</span>
          </div>
        </div>
        <div className="flex flex-col w-screen box-border h-screen items-center justify-start pt-[12vh] snap-center ">
          <h1 className="mb-[8px]  font-bold text-[5vw]">Top Tasks</h1>
          <div className="flex items-center justify-start w-[98vw] h-[85%] box-border overflow-x-scroll snap-x snap-mandatory px-[7%] scroll-pl-4 scrollbar-hide">
            <Task url='/Assets/images/image1.JPG' title='Dream Job Finder' description='This project will help you to improve your app development skills. We provide designs and assets to  develop the ui. You can also code with flutter or Java' />
            <Task url='/Assets/images/image1.JPG' title='Dream Job Finder' description='This project will help you to improve your app development skills. We provide designs and assets to  develop the ui. You can also code with flutter or Java' />
            <Task url='/Assets/images/image1.JPG' title='Dream Job Finder' description='This project will help you to improve your app development skills. We provide designs and assets to  develop the ui. You can also code with flutter or Java' />
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
