import type { NextPage } from 'next'
import Head from 'next/head'
import { Toaster } from 'react-hot-toast'
import Carousel from '../components/Carousel'
import CheckInternetConnection from '../components/CheckInternetConnection'
import Footer from '../components/Footer'
import Header from '../components/Header'
import NavBar from '../components/NavBar'
import styles from '../styles/desktop.module.css';


const Home: NextPage = () => {



  return (
    <CheckInternetConnection>
    <div className={` box-border overflow-y-scroll snap-y snap-mandatory scrollbar-hide`}>
      <Head>
        <title>DevsUI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className=" z-[-1] w-screen h-screen ">
      <NavBar />
        <Header />

        {/* ---------------  second page with discord logo starts here ---------------------- */}

        <div className={`${styles.SiteDetails} w-screen h-screen flex flex-col items-center justify-start pt-[13vh] snap-center`}>
          <div className={`self-center w-[95%]  h-[16vh]  rounded-[15px] mb-[2vh]  bg-discord bg-[#5965f1] bg-fit bg-no-repeat bg-center flex items-end shadow-task justify-center sm:pt-[12vh] sm:h-[25vh] sm:max-h-[300px]  sm:pb-[10px] sm:bg-center sm:bottom-[2.5rem] sm:mb-[18vh]`}>
            <h1 className={`hidden sm:block text-white font-semibold text-[1.3rem]  tracking-wide`}>Connect  with  1000+  people  through  Discord</h1>
          </div>
          <div className={`flex flex-col items-center h-[65vh] pt-[2vh] justify-start sm:flex-row sm:w-[80%]`}>
            <div className={`flex flex-col items-center justify-center`}>
              <img src="/Assets/lightmode/choose-icon.png" className={`${styles.image1} w-[15%]  sm:w-[40%]`} />
              <span className={`${styles.image1Text} text-[5vw] max-w-[60%] text-center mt-[7px] mb-[7px] sm:text-[25px] sm:max-w-[80%]`}>Choose your topic or design from us</span>
            </div>
            <div className={`flex flex-col items-center justify-center`}>
              <img src="/Assets/lightmode/design-dev.png" className={`${styles.image2} w-[15%] sm:w-[38%]`} />
              <span className={`${styles.image2Text} text-[5vw] max-w-[60%] text-center mt-[7px] mb-[7px] sm:text-[25px] sm:max-w-[60%]`}>Develop or design your item</span>
            </div>
            <div className={`flex flex-col items-center justify-center`}>
              <img src="/Assets/lightmode/publish-icon.png" className={`${styles.image3} w-[14%] sm:w-[30%]`} />
              <span className={`${styles.image3Text} text-[5vw] max-w-[60%] text-center mt-[7px] mb-[7px] sm:text-[25px] sm:max-w-[80%]`}>Publish on our site and support others</span>
            </div>
          </div>
        </div>

        {/* ---------------  second page with discord logo ends here ---------------------- */}

        {/* ---------------  third page with top challenged starts here ---------------------- */}


        <div className={`flex flex-col w-screen box-border h-screen items-center justify-start pt-[11vh] snap-center`}>
          <h1 className={`mb-[8px]  font-bold text-[5vw] sm:text-[2vw]`}>Top Challenges</h1>

          {/* ------ component which contains all challenge cards ----------*/}
          <Carousel />
          {/* ------ component which contains all challenge cards ----------*/}

        </div>

        {/* ---------------  third page with top challenged ends here ---------------------- */}


        <Footer position='relative'/>
      </div>
      <Toaster />
    </div>
    </CheckInternetConnection>
  )
}

export default Home
