import React, { useState } from 'react'
import { NextPage } from 'next'
import Head from 'next/head'
import NavBar from '../../components/NavBar'
import CheckBox from '../../components/CheckBox'
import { check, ToolsUsed } from '../../constants/types'
import UploadContent from '../../components/UploadContent'
import DesignTools from '../../components/DesignTools'
import ItemsProvided from '../../components/ItemsProvided'
import Footer from '../../components/Footer'
import MiniFooter from '../../components/MiniFooter'


const UploadDesign: NextPage = () => {
  const [checked, setChecked] = useState<check>(null);
  const [levelChecked, setLevelChecked] = useState<check>(null)
  const [uploadedDetails,setUploadedDetails] = useState<Array<string>>([] as Array<string>);
  const [toolsUsed, setToolsUsed] = useState<Array<ToolsUsed>>([])

  const addCheckMark = (current: check) => {
    setChecked(current)
    if (checked === current) {
      setChecked(null)
    }
  }

  const addLevelCheckMark = (level: check) => {
    setLevelChecked(level)
    if (levelChecked === level) {
      setLevelChecked(null)
    }
  }

  const addFileType = (type:string) => {
    if(uploadedDetails.includes(type)){
      setUploadedDetails(uploadedDetails.filter((items) => items !== type))
    }
    else {
      setUploadedDetails([...uploadedDetails,type])
    }
  }

  const addTool = (name:ToolsUsed) => {
    if(toolsUsed.includes(name)){
      setToolsUsed(toolsUsed.filter((items) => items !== name))
    }
    else {
      setToolsUsed([...toolsUsed,name])
    }
  }

  return (
    <div className='w-screen h-screen flex flex-col items-center justify-start pt-[10vh] sm:items-start sm:box-border'>
      <Head>
        <title>DevsUI 🌩️ </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconhttps://www.getdroidtips.com/realme-narzo-10a-firmware-flash-file/#google_vignette.ico" />
      </Head>
      <NavBar />
      <div className="w-[100%] h-[100%] flex flex-col overflow-y-scroll scrollbar-hide ">
        <div className="w-[100%] flex flex-col box-border px-5 sm:px-[45px]">
        <h1 className="text-[8vw] mt-3  sm:text-[2vw] esm:text-[6.8vw] asm:text-[7vw]">Upload Design</h1>
        <input type="text" placeholder='Name' className=" w-[85%] h-[6%] min-h-[40px] focus:outline-none bg-gray-200 rounded-[10px] mt-5 my-3 pl-5 sm:w-[30%] sm:max-w-[350px]" />
        <input type="text" placeholder='Description' className=" w-[85%] h-[15%] focus:outline-none min-h-[80px] bg-gray-200 rounded-[10px] my-3 pl-5 sm:w-[30%] sm:max-w-[350px] sm:min-h-[120px]" />
        <div className="w-[100%] h-[10%] flex flex-col my-1 esm:my-2">
          <span className="text-gray-500 text-[4vw] sm:text-[1vw] sm:font-bold">Upload designs in PNG or JPG format</span>
          <div className="flex items-center justify-start mt-2 w-[100%] h-[100%] esm:mt-5">
            <button className='w-[35%] h-[85%] min-h-[35px] min-w-[120px] focus:outline-none rounded-[10px] flex items-center justify-center bg-gray-200 text-gray-500 text-[4vw] esm:text-[3.4vw] asm:text-[3vw] msm:text-[2.5vw] sm:text-[0.8vw]'>Upload File</button>
          </div>
        </div>
        <div className="w-[100%] h-[20%] flex  items-start  mt-5 sm:w-[30%] esm:mt-[35px] esm:w-[90%] asm:w-[80%] msm:w-[75%]">
          <span className="font-semibold text-gray-500">completed:</span>
          <CheckBox percentage={'25%'} checked={checked === '25%' ? true : false} onClick={() => addCheckMark('25%')} />
          <CheckBox percentage={'50%'} checked={checked === '50%' ? true : false} onClick={() => addCheckMark('50%')} />
          <CheckBox percentage={'75%'} checked={checked === '75%' ? true : false} onClick={() => addCheckMark('75%')} />
          <CheckBox percentage={'100%'} checked={checked === '100%' ? true : false} onClick={() => addCheckMark('100%')} />
        </div>
        <div className="w-[100%] h-auto  flex flex-col my-2 esm:my-2">
          <UploadContent title='Figma file access' checked={uploadedDetails.includes('Figma file')?true:false} onClick={() => addFileType('Figma file')} />
          <UploadContent title='Sketch file access' checked={uploadedDetails.includes('Sketch file')?true:false} onClick={() => addFileType('Sketch file')} />
          <UploadContent title='Optimized image assets' checked={uploadedDetails.includes('Image Assets')?true:false} onClick={() => addFileType('Image Assets')} />
        </div>
        <div className="w-[100%] h-auto flex flex-col ">
          {
            uploadedDetails.map((item,index) => (
              <div key={index} className="w-[100%] h-[50%] flex flex-col my-2 cursor-pointer">
              <span className="text-gray-500 text-[7vw] sm:text-[1.4vw] esm:text-[5vw] asm:text-[4.4vw] msm:text-[4vw]">Upload {item}</span>
              <div className="w-[100%] h-[70%] flex mt-3">
                <button className='w-[35%] h-[85%] min-h-[35px] min-w-[120px] focus:outline-none rounded-[10px] flex items-center justify-center bg-gray-200 text-gray-500 text-[4vw] esm:text-[3.4vw] asm:text-[3vw] msm:text-[2.5vw] sm:text-[0.8vw] sm:w-[10%]'>Upload {item}</button>
              </div>
            </div>
            ))
          }
        </div>
        <div className="w-[100%] h-[20%] flex  items-start  mt-5  my-0 sm:w-[30%] sm:my-5 esm:w-[90%] asm:w-[80%] msm:w-[75%]">
          <span className="font-semibold text-gray-500">Levels:</span>
          <CheckBox percentage={'1'} checked={levelChecked === '1' ? true : false} onClick={() => addLevelCheckMark('1')} />
          <CheckBox percentage={'2'} checked={levelChecked === '2' ? true : false} onClick={() => addLevelCheckMark('2')} />
          <CheckBox percentage={'3'} checked={levelChecked === '3' ? true : false} onClick={() => addLevelCheckMark('3')} />
          <CheckBox percentage={'4'} checked={levelChecked === '4' ? true : false} onClick={() => addLevelCheckMark('4')} />
        </div>
        <div className="w-[100%] h-[10%] flex flex-col  sm:w-[50%]">
          <span className="text-gray-500 font-semibold my-2 text-[4vw] sm:text-[1vw]">Tools Used</span>
          <div className=" w-[100%] h-[90%] flex items-center">
           <DesignTools url='/Assets/icons/figma.png' checked={toolsUsed.includes('Figma')?true:false} onClick={() => addTool('Figma')} />
           <DesignTools url='/Assets/icons/xd.png' checked={toolsUsed.includes('XD')?true:false} onClick={() =>addTool('XD')}/>
           <DesignTools url='/Assets/icons/after-effects.png' checked={toolsUsed.includes('AE')?true:false} onClick={() =>addTool('AE')}/>
           <DesignTools url='/Assets/icons/illustrator.png' checked={toolsUsed.includes('Illustrator')?true:false} onClick={() =>addTool('Illustrator')}/>
           <DesignTools url='/Assets/icons/photoshop.png' checked={toolsUsed.includes('Photoshop')?true:false} onClick={() =>addTool('Photoshop')}/>
           <DesignTools url='/Assets/icons/sketch.png' checked={toolsUsed.includes('Sketch')?true:false} onClick={() =>addTool('Sketch')}/>
          </div>
        </div>
        <button className=' min-w-[60px] max-w-[150px] min-h-[35px] bg-[#323c71] max-h-[45px] rounded-[10px] text-white flex items-center justify-center focus:outline-none mt-8 mb-4 text-[4vw] esm:text-[3.4vw] asm:text-[3vw] msm:text-[2.5vw] sm:text-[0.8vw] esm:my-[50px]'>Upload Design</button>
        </div>
        <Footer />
      </div>
    </div>
  )
}

export default UploadDesign